{% set data = load_setup_py_data() %}

package:
  name: wsp-gtam-tools
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
  run:
    - python >=3.6
    - bokeh
    - geopandas >=0.9.0
    - numpy
    - pandas
    - wsp-balsa >=1.2.2
    - wsp-cheval

about:
  home: https://github.com/sap-toronto/gtam-tools
  license: MIT
  license_file: LICENSE
  summary: A Python package for handling GTAModel data

extra:
  maintainers:
    - Brian Cheung
